# Site settings
title: System-on-Chip Design & Verification
author:
  name: Bartlomiej Drapinski
  email:
description: "FPGA VGA Project Blog"

# Build settings
remote_theme: jekyll/minima

feed:
  enabled: false

